name: blockies_svg
description: Etherum Blockies implementation
version: 1.0.2

environment:
  sdk: '>=2.19.0-0 <4.0.0'
  flutter: ">=3.7.0-0"

dependencies:
  fixnum: ^1.1.0
  flutter:
    sdk: flutter
  
dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter: